dist: trusty
language: python

python:
  - "2.7"

env:
  global:
    - ENCRYPTION_LABEL: "4cbf8f60a106"
    - COMMIT_AUTHOR_EMAIL: "howtohackitalia@gmail.com"

script:
  - bash .github/build.sh

branches:
  only:
    - master
    # Add more branches if required
